# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np
arr = np.random.randint(0, 20, size=(4, 7))
norm_arr=(arr-np.min(arr))/(np.max(arr)-np.min(arr))
print(f'массив arr \n {arr},\n массив arr с номализованными значениями:\n {norm_arr}')

массив arr 
 [[17 10 10 15  0 18 19]
 [19 11 11  5  5 18 16]
 [ 6  6 17 12 14  3 10]
 [14  7 10  5  0  2 13]],
 массив arr с номализованными значениями:
 [[0.89473684 0.52631579 0.52631579 0.78947368 0.         0.94736842
  1.        ]
 [1.         0.57894737 0.57894737 0.26315789 0.26315789 0.94736842
  0.84210526]
 [0.31578947 0.31578947 0.89473684 0.63157895 0.73684211 0.15789474
  0.52631579]
 [0.73684211 0.36842105 0.52631579 0.26315789 0.         0.10526316
  0.68421053]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [1]:
arr = np.random.randint(0, 20, size=(8, 10))
print(arr)
summ=np.min(arr, axis=1)
print(summ)
ind=np.argmin(summ)
print('min str -\n', arr[ind])

NameError: name 'np' is not defined

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
import numpy as np
ar = np.loadtxt('minutes_n_ingredients.csv', delimiter=',',skiprows=1, dtype=np.int32)
arr1=ar.copy()
print(ar[0:5, :])

#arr1

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [48]:
#print(ar)
aver1=np.mean(ar[0:,1])
aver2=np.mean(ar[0:, 2])

min1=np.min(ar[:,1])
min2=np.min(ar[:,2])

max1=np.max(ar[:,1])
max2=np.max(ar[:,2])

med1=np.median(arr1[:,1])
med2=np.median(arr1[:,2])
print(f'средние значения: {aver1,aver2}\n мининмум: {min1,min2}\n максимум: {max1,max2}\n медианные значения: {med1,med2}')

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]
средние значения: (21601.00169, 9.05528)
 мининмум: (0, 1)
 максимум: (2147483647, 39)
 медианные значения: (40.0, 9.0)


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [49]:
arr_lim=np.quantile(ar[:,1],q=0.75)
print(arr_lim)

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [57]:
n=(ar[:,1]==0).sum()
ar3=np.place(arr1[:,1],arr1[:,1]==0, 1)
print(np.min(arr1))#минимальная продолжительность рецепта
print(n)#количество рецептов равных нулю

1
479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [54]:
rec=np.unique(ar[:,0])
print(len(rec))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [59]:
ing=(np.unique(ar[:,2]))
print(len(ing),ing)

37 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [50]:
arr5=ar[ar[:,2]<=5]
print(arr5)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [25]:
av_ingr=arr1[:, 2]/arr1[:, 1]
av_ingr_max=np.max(av_ingr)
print(av_ingr,av_ingr_max)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ] inf


C:\Users\kdubi\AppData\Local\Temp\ipykernel_21624\3250987986.py:1: RuntimeWarning: divide by zero encountered in true_divide
  av_ingr=arr1[:, 2]/arr1[:, 1]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [24]:
top_av=arr1[np.argsort(arr1[:, 1])][-100:, 2]
top_av=np.average(top_av)
print(top_av)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [69]:
rec_rand=arr1[np.random.randint(arr1.shape[0], size=10)]
print(rec_rand)

[[159870     20     17]
 [211569     25      8]
 [238679     30     13]
 [ 53266     65     15]
 [278082     15      6]
 [254063     50      5]
 [473163     30      6]
 [175916     40      6]
 [476503     50      7]
 [144175     35      5]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [67]:
av_rec=np.average(arr1[:,2])#среднее кол-во ингредиентов в рецепте  
num=(arr1[:,2]<av_rec).sum()/len(arr1[:,2])*100

print(num)

9.05528 58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [4]:
easy_res=(arr1[:,1]<=20) & (arr1[:,2]<=5)
#easy_res.dtype=np.int32
    

ar4=np.hstack((arr1,easy_res[:, np.newaxis]))

print(arr1)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


13. Выведите процент "простых" рецептов в датасете

In [74]:
q=ar4[ar4[:,3]==1, 3].sum()/ar4.shape[0]*100
#print(ar4[ar4[:,3]==1,3].sum())
print(q)

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [21]:
arr_short=arr1[arr1[:,1]<=10]
arr_mid=arr1[arr1[:,1]>10]<=20
#arr_mid1=arr_mid[arr_mid<=20]
arr_long=arr1[arr1[:,1]>20]
'''
print(arr_short.shape)
print(arr_mid.shape)#минимальное число рецептов в группе это 12466,зн ширина массива не более 12466
print(arr_long.shape)
'''

arr_3d=np.arange(112194).reshape(3,12466,3)
#arr_3d=np.arange(149592).reshape(4,12466,3)
arr_3d[0]=arr_short[:12466, :]
arr_3d[1]=arr_mid[:12466,:]
arr_3d[2]=arr_long[:12466, :]

print(arr_3d.shape)
print(arr_3d)

(4, 12466, 3)


array([[[ 94746,     10,      6],
        [ 67660,      5,      6],
        [366174,      7,      9],
        ...,
        [420725,      5,      3],
        [  4747,      0,      9],
        [370915,      5,      4]],

       [[     0,      0,      1],
        [     0,      0,      1],
        [     0,      0,      1],
        ...,
        [     0,      0,      1],
        [     0,      0,      1],
        [     0,      0,      1]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [ 68428,     70,     10],
        [312995,   1445,      7],
        [ 93651,    240,     12]],

       [[112194, 112195, 112196],
        [112197, 112198, 112199],
        [112200, 112201, 112202],
        ...,
        [149583, 149584, 149585],
        [149586, 149587, 149588],
        [149589, 149590, 149591]]])

In [18]:
3*12466*4

149592